# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1f\n\x11RequisicaoUsuario\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x0fRespostaUsuario\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\"\n\x0fRequisicaoDados\x12\x0f\n\x07valores\x18\x01 \x03(\x02\"3\n\x14RespostaEstatisticas\x12\r\n\x05media\x18\x01 \x01(\x02\x12\x0c\n\x04soma\x18\x02 \x01(\x02\x32\x44\n\x08ServicoA\x12\x38\n\x10\x43onsultarUsuario\x12\x12.RequisicaoUsuario\x1a\x10.RespostaUsuario2K\n\x08ServicoB\x12?\n\x14\x43\x61lcularEstatisticas\x12\x10.RequisicaoDados\x1a\x15.RespostaEstatisticasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUISICAOUSUARIO']._serialized_start=17
  _globals['_REQUISICAOUSUARIO']._serialized_end=48
  _globals['_RESPOSTAUSUARIO']._serialized_start=50
  _globals['_RESPOSTAUSUARIO']._serialized_end=96
  _globals['_REQUISICAODADOS']._serialized_start=98
  _globals['_REQUISICAODADOS']._serialized_end=132
  _globals['_RESPOSTAESTATISTICAS']._serialized_start=134
  _globals['_RESPOSTAESTATISTICAS']._serialized_end=185
  _globals['_SERVICOA']._serialized_start=187
  _globals['_SERVICOA']._serialized_end=255
  _globals['_SERVICOB']._serialized_start=257
  _globals['_SERVICOB']._serialized_end=332
# @@protoc_insertion_point(module_scope)
