# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServicoAStub(object):
    """Serviço do Módulo A (Python)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarUsuario = channel.unary_unary(
                '/ServicoA/ConsultarUsuario',
                request_serializer=service__pb2.RequisicaoUsuario.SerializeToString,
                response_deserializer=service__pb2.RespostaUsuario.FromString,
                )


class ServicoAServicer(object):
    """Serviço do Módulo A (Python)
    """

    def ConsultarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarUsuario,
                    request_deserializer=service__pb2.RequisicaoUsuario.FromString,
                    response_serializer=service__pb2.RespostaUsuario.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServicoA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServicoA(object):
    """Serviço do Módulo A (Python)
    """

    @staticmethod
    def ConsultarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServicoA/ConsultarUsuario',
            service__pb2.RequisicaoUsuario.SerializeToString,
            service__pb2.RespostaUsuario.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ServicoBStub(object):
    """Serviço do Módulo B (Python)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalcularEstatisticas = channel.unary_unary(
                '/ServicoB/CalcularEstatisticas',
                request_serializer=service__pb2.RequisicaoDados.SerializeToString,
                response_deserializer=service__pb2.RespostaEstatisticas.FromString,
                )


class ServicoBServicer(object):
    """Serviço do Módulo B (Python)
    """

    def CalcularEstatisticas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicoBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalcularEstatisticas': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularEstatisticas,
                    request_deserializer=service__pb2.RequisicaoDados.FromString,
                    response_serializer=service__pb2.RespostaEstatisticas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServicoB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServicoB(object):
    """Serviço do Módulo B (Python)
    """

    @staticmethod
    def CalcularEstatisticas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServicoB/CalcularEstatisticas',
            service__pb2.RequisicaoDados.SerializeToString,
            service__pb2.RespostaEstatisticas.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
