# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04\x64\x65mo\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tEchoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\nNumRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x1a\n\x08NumReply\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x17\n\x08SumReply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"+\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xeb\x01\n\x0b\x44\x65moService\x12\x31\n\tUnaryEcho\x12\x11.demo.EchoRequest\x1a\x0f.demo.EchoReply\"\x00\x12\x38\n\x10ServerStreamNums\x12\x10.demo.NumRequest\x1a\x0e.demo.NumReply\"\x00\x30\x01\x12\x37\n\x0f\x43lientStreamSum\x12\x10.demo.NumRequest\x1a\x0e.demo.SumReply\"\x00(\x01\x12\x36\n\x08\x42idiChat\x12\x11.demo.ChatMessage\x1a\x11.demo.ChatMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=23
  _globals['_ECHOREQUEST']._serialized_end=53
  _globals['_ECHOREPLY']._serialized_start=55
  _globals['_ECHOREPLY']._serialized_end=83
  _globals['_NUMREQUEST']._serialized_start=85
  _globals['_NUMREQUEST']._serialized_end=112
  _globals['_NUMREPLY']._serialized_start=114
  _globals['_NUMREPLY']._serialized_end=140
  _globals['_SUMREPLY']._serialized_start=142
  _globals['_SUMREPLY']._serialized_end=165
  _globals['_CHATMESSAGE']._serialized_start=167
  _globals['_CHATMESSAGE']._serialized_end=210
  _globals['_DEMOSERVICE']._serialized_start=213
  _globals['_DEMOSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
