# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DemoServiceStub(object):
    """Definição do serviço com os 4 tipos de RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnaryEcho = channel.unary_unary(
                '/demo.DemoService/UnaryEcho',
                request_serializer=service__pb2.EchoRequest.SerializeToString,
                response_deserializer=service__pb2.EchoReply.FromString,
                _registered_method=True)
        self.ServerStreamNums = channel.unary_stream(
                '/demo.DemoService/ServerStreamNums',
                request_serializer=service__pb2.NumRequest.SerializeToString,
                response_deserializer=service__pb2.NumReply.FromString,
                _registered_method=True)
        self.ClientStreamSum = channel.stream_unary(
                '/demo.DemoService/ClientStreamSum',
                request_serializer=service__pb2.NumRequest.SerializeToString,
                response_deserializer=service__pb2.SumReply.FromString,
                _registered_method=True)
        self.BidiChat = channel.stream_stream(
                '/demo.DemoService/BidiChat',
                request_serializer=service__pb2.ChatMessage.SerializeToString,
                response_deserializer=service__pb2.ChatMessage.FromString,
                _registered_method=True)


class DemoServiceServicer(object):
    """Definição do serviço com os 4 tipos de RPC
    """

    def UnaryEcho(self, request, context):
        """1. Unary RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamNums(self, request, context):
        """2. Server-streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamSum(self, request_iterator, context):
        """3. Client-streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidiChat(self, request_iterator, context):
        """4. Bidirectional-streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnaryEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.UnaryEcho,
                    request_deserializer=service__pb2.EchoRequest.FromString,
                    response_serializer=service__pb2.EchoReply.SerializeToString,
            ),
            'ServerStreamNums': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamNums,
                    request_deserializer=service__pb2.NumRequest.FromString,
                    response_serializer=service__pb2.NumReply.SerializeToString,
            ),
            'ClientStreamSum': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamSum,
                    request_deserializer=service__pb2.NumRequest.FromString,
                    response_serializer=service__pb2.SumReply.SerializeToString,
            ),
            'BidiChat': grpc.stream_stream_rpc_method_handler(
                    servicer.BidiChat,
                    request_deserializer=service__pb2.ChatMessage.FromString,
                    response_serializer=service__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.DemoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.DemoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DemoService(object):
    """Definição do serviço com os 4 tipos de RPC
    """

    @staticmethod
    def UnaryEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.DemoService/UnaryEcho',
            service__pb2.EchoRequest.SerializeToString,
            service__pb2.EchoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStreamNums(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/demo.DemoService/ServerStreamNums',
            service__pb2.NumRequest.SerializeToString,
            service__pb2.NumReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientStreamSum(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/demo.DemoService/ClientStreamSum',
            service__pb2.NumRequest.SerializeToString,
            service__pb2.SumReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BidiChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/demo.DemoService/BidiChat',
            service__pb2.ChatMessage.SerializeToString,
            service__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
